name: ReadMe

on:
  push:
    branches: [DISABLED]

jobs:
  readme:
    runs-on: ubuntu-latest
    if: false
    env:
      PORT: 4000
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: start node server
        run: |
          node readme.js > /dev/null &

      - name: make request
        run: |
          SVG=$(curl localhost:${PORT}/svg)
          echo $SVG > profile.svg
          echo '<img src="profile.svg">' >> README.md
          git add profile.svg README.md
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -m "added svg to readme"
          git push

  build:
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: echo pass
