name: "Test Workflow"

on:
  # pull_request:
  #   branches: github-action-ec2
  #   types:
  #     - opened
  #     - closed
  # pull_request_target:
  #   branches: github-action-ec2
  #   types: synchronize
  push:

jobs:
  build:
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest]
    # runs-on: ${{ matrix.os }}

    runs-on: ubuntu-latest
    env:
      SANDI_KP: ${{secrets.SANDI_KP}}
    steps:
      - name: "Create html for upload"
        run: |
          mkdir workflow-files
          echo "<h1>This is html created by a job and uploaded!</h1><p>Added this <pre> to trigger workflow</pre>" > workflow-files/workflow.html

      - name: create file
        run: |
          echo ${SANDI_KP} > workflow-files/sandi-secret.pem

      - name: "Artifact upload"
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./workflow-files

  # if: github.event.pull_request.merged == true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download file
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: use file
        run: |
          scp -i sandi-secret.pem sandi-secret.pem ubuntu@54.237.63.11:/ubuntu
