name: "Test Workflow"

on:
  pull_request:
    branches:
    - github-action-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_ENV_1: ${{secrets.MY_ENV_1}}
  
    steps:
      - name: "bad command"
        run: cda $MY_ENV_1