name: "Test Workflow"

on:
  pull_request:
    branches:
    - github-action-ec2

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ maxtrix.os }}
    env:
      MY_ENV_1: ${{secrets.MY_ENV_1}}
  
    steps:
      - name: "bad command"
        run: echo $MY_ENV_1