name: "Test Workflow"

on:
  # pull_request:
  #   branches: github-action-ec2
  #   types:
  #     - opened
  #     - closed
  # pull_request_target:
  #   branches: github-action-ec2
  #   types: synchronize
  push:

env:
  SANDI_KP: ${{ secrets.SANDI_KP }}

jobs:
  build:
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest]
    # runs-on: ${{ matrix.os }}

    runs-on: ubuntu-latest
    env:
      MY_ENV_1: ${{secrets.MY_ENV_1}}
    steps:
      - name: "Create html for upload"
        run: |
          mkdir build-files
          echo "<h1>This is html created by a job and uploaded!</h1><p>Added this <pre> to trigger workflow</pre>" > build-files/workflow.html

      - name: create file
        run: |
          echo ${MY_ENV_1} > build-files/dummyfile

      - name: "Artifact upload"
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./build-files

  # if: github.event.pull_request.merged == true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download file
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: build-files

      - name: use file
        run: |
          cat ${SANDI_KP}
          # cat build-files/dummyfile

      - name: copy file with appleboy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 54.237.63.11
          username: ubuntu
          key: ${SANDI_KP}
          source: build-files/dummyfile
          target: /home/ubuntu

        # scp -v -o StrictHostKeyChecking=no -i ${{ secrets.MY_ENV_1 }} sandi-secret.pem ubuntu@54.237.63.11:/ubuntu
        # scp -v -o StrictHostKeyChecking=no -i sandi-secret.pem sandi-secret.pem ubuntu@54.237.63.11:/ubuntu
